sudo: required
services:
  - docker

before_install:
  - docker build -t mcritic/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mcritic/react-test npm test -- --coverage

after_success:
  - docker build -t mcritic/multi-client ./client
  - docker build -t mcritic/multi-nginx ./nginx
  - docker build -t mcritic/multi-server ./server
  - docker build -t mcritic/multi-worker ./worker
  # Log in to the docker CLI
  - echo $DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push mcritic/multi-client
  - docker push mcritic/multi-nginx
  - docker push mcritic/multi-server
  - docker push mcritic/multi-worker
